package edu.ntnu.stud.idatg2003.backend.engine;

import edu.ntnu.stud.idatg2003.backend.mathoperations.Matrix2x2;
import edu.ntnu.stud.idatg2003.backend.mathoperations.Vector2D;
import edu.ntnu.stud.idatg2003.backend.transformations.AffineTransform2D;


/**
 * The {@code ChaosCanvas} class represents a canvas
 * for drawing a fractal generated by the chaos game algorithm.
 * It maintains a 2D array to represent the canvas where the fractal will be drawn.
 * Each element in the array indicates whether a pixel should be drawn (1) or not (0).
 * The canvas supports transformations from fractal coordinates to canvas pixel indices,
 * allowing fractal points to be accurately plotted on the canvas.
 *
 * @version 0.0.3
 * @since 0.0.1 (The version of ChaosGameEngine application when introduced)
 */
public class ChaosCanvas {

  private final int[][] canvas;     // 2D array representing the canvas
  private final int width;          // Width of the canvas in pixels
  private final int height;         // Height of the canvas in pixels
  private final Vector2D minCoords; // lower left corner coordinates of the fractal space
  private final Vector2D maxCoords; // upper right corner coordinates of the fractal space

  // Transformation from fractal coordinates to canvas pixel indices:
  private AffineTransform2D transformCoordsToIndices;





  /**
   * Constructs a new {@code ChaosCanvas} object with specified dimensions and coordinate bounds.
   * Initializes the transformation needed to map fractal coordinates to canvas pixel indices and
   * clear the canvas.
   *
   * @param width The width of the canvas in pixels.
   * @param height The height of the canvas in pixels.
   * @param minCoords The lower left corner coordinates of the fractal space.
   * @param maxCoords The upper right corner coordinates of the fractal space
   * @since 0.0.1
   */
  public ChaosCanvas(int width, int height, Vector2D minCoords, Vector2D maxCoords) {
    this.width = width;
    this.height = height;
    this.minCoords = minCoords;
    this.maxCoords = maxCoords;
    this.canvas = new int[height][width];
    initializeTransformation();
    clearCanvas();
  }




  /**
   * Initializes the transformation used to convert points
   * from fractal coordinates to canvas pixel indices.
   * This involves creating a scaling matrix based on the canvas size and
   * the coordinate bounds, and then
   * creating an affine transformation that incorporates both scaling and translation.
   *
   * @since 0.0.3
   */
  private void initializeTransformation() {
    // Calculating the scale factors from fractal space to canvas space:
    double scaleX = (width - 1) / (maxCoords.getX0() - minCoords.getX0());
    double scaleY = (height - 1) / (maxCoords.getX1() - minCoords.getX1());

    // Creating the matrix with scale factors:
    Matrix2x2 scaleMatrix = new Matrix2x2(scaleX, 0, 0, scaleY);

    // Calculating the translation vector to shift the coordinates:
    Vector2D translationVector =
        new Vector2D(-minCoords.getX0() * scaleX, -minCoords.getX1() * scaleY);

    // Creating the AffineTransform2D with the matrix and vector:
    this.transformCoordsToIndices = new AffineTransform2D(scaleMatrix, translationVector);
  }




  /**
   * Transforms the given point in fractal coordinates to canvas pixel indices,
   * ensuring the point lies within the bounds of the canvas.
   *
   * @param point The point in fractal coordinates to transform.
   * @return The corresponding canvas point as a {@link Vector2D} of pixel indices.
   * @throws IndexOutOfBoundsException If the transformed point is outside the canvas bounds.
   * @since 0.0.3
   */
  private Vector2D transformToCanvasIndices(Vector2D point) {
    Vector2D canvasPoint = transformCoordsToIndices.transform(point);
    int xIndex = (int) canvasPoint.getX0();
    int yIndex = (int) canvasPoint.getX1();
    if (xIndex < 0 || xIndex >= width || yIndex < 0 || yIndex >= height) {
      throw new IndexOutOfBoundsException("Point transformed to canvas coordinates is out of bounds.");
    }
    return canvasPoint;
  }




  /**
   * Retrieves the value of a pixel at the given point in fractal coordinates.
   * This method first transforms the fractal coordinates to canvas pixel indices,
   * then returns the value of the pixel at that location.
   *
   * @param point The point in fractal coordinates.
   * @return The value of the pixel at the transformed location, 0 (not drawn) or 1 (drawn).
   * @since 0.0.1
   */
  public int getPixel(Vector2D point) {
    Vector2D canvasPoint = transformToCanvasIndices(point);
    return canvas[(int) canvasPoint.getX1()][(int) canvasPoint.getX0()];
  }




  /**
   * Puts a pixel with the specified color at the given point in fractal coordinates on the canvas.
   * The fractal coordinates are transformed to canvas pixel indices,
   * and the color is set at that location.
   *
   * @param point The point in fractal coordinates where the pixel should be placed.
   * @param color The color value for the pixel, 0 (clear) or 1 (drawn).
   * @since 0.0.1
   */
  public void putPixel(Vector2D point, int color) {
    Vector2D canvasPoint = transformToCanvasIndices(point);
    canvas[(int) canvasPoint.getX1()][(int) canvasPoint.getX0()] = color;
  }




  /**
   * Retrieves the entire canvas as a 2D array of integers,
   * where each element represents a pixel's color value.
   * A value of 0 indicates that a pixel is not drawn,
   * and a value of 1 indicates that a pixel is drawn.
   *
   * @return The 2D array representing the canvas.
   * @since 0.0.1
   */
  public int[][] getCanvasArray() {
    return canvas;
  }




  /**
   * Clears the canvas by setting all pixels to 0, indicating that no pixels are drawn.
   *
   * @since 0.0.1
   */
  public void clearCanvas() {
    for (int i = 0; i < height; i++) { // 1. loop is for rows (height)
      for (int j = 0; j < width; j++) { // 2. loop is for columns (width)
        canvas[i][j] = 0;
      }
    }
  }

}
