package edu.ntnu.stud.idatg2003.engine;

import edu.ntnu.stud.idatg2003.mathoperations.Matrix2x2;
import edu.ntnu.stud.idatg2003.mathoperations.Vector2D;
import edu.ntnu.stud.idatg2003.transformation.AffineTransform2D;


/**
 * {@code ChaosGame} class represents a canvas for drawing a fractal generated by a chaos game.
 * The canvas is represented as a 2D array of integers, where each element is either 0 or 1.
 * The canvas has a fixed size, and the coordinates of the lower left and upper right corners.
 *
 * @version 0.0.1
 * @since 0.0.1
 */
public class ChaosCanvas {

  private final int[][] canvas;
  private final Vector2D minCoords;
  private final Vector2D maxCoords;
  private final int width;
  private final int height;
  private AffineTransform2D transformCoordsToIndices;


  /**
   * Constructs a  new {@code ChaosCanvas} object with the specified with,
   * height and coordinates of the lower left and upper right corners.
   *
   * @param width The width of the canvas.
   * @param height The height of the canvas.
   * @param minCoords Coordinates of the lower left corners of the drawing area.
   * @param maxCoords Coordinates of the upper right corners of the drawing area.
   * @since 0.0.1
   */
  public ChaosCanvas(int width, int height, Vector2D minCoords, Vector2D maxCoords) {
    this.width = width;
    this.height = height;
    this.minCoords = minCoords;
    this.maxCoords = maxCoords;
    canvas = new int[width][height];
  }


  /**
   * Transforms the given point in the coordinate system to pixel indices.
   *
   * @param point The point in the coordinate system.
   * @return The pixel indices of the given point.
   * @throws IllegalArgumentException If the point is null.
   * @since 0.0.1
   */
  public Vector2D getPixel(Vector2D point) {
    //System.out.println("before: " + point.getX0() + " " + point.getX1());
    // Calculating affine transformation from coordinates to pixel indices
    double scaleX0 = (width - 1) / (maxCoords.getX0() - minCoords.getX0());
    double scaleX1 = (height - 1) / (minCoords.getX1() - maxCoords.getX1());

    // Calculation of offsetX0 and offsetX1
    double offsetX0 = ((height - 1) * maxCoords.getX1()) / (maxCoords.getX1() - minCoords.getX1());
    double offsetX1 = ((width - 1) * minCoords.getX0()) / (minCoords.getX0() - maxCoords.getX0());

    // the "A" matrix that decides how the coordinates are scaled and rotated:
    double[][] matrixArray = {{0, scaleX1},
        {scaleX0, 0}};

    Matrix2x2 matrixA = new Matrix2x2(matrixArray);

    // the "b" vector that decides how the coordinates are translated, or going to move:
    Vector2D translationVectorB = new Vector2D(offsetX0, offsetX1);

    // Applying the affine transformation to the input point
    transformCoordsToIndices = new AffineTransform2D(matrixA, translationVectorB);
    //System.out.println("after: " + point.getX0() + " " + point.getX1());
    return transformCoordsToIndices.transform(point);
  }


  /**
   * Puts a pixel at the specified point in the canvas.
   *
   * @param point The point to put the pixel at.
   * @throws IllegalArgumentException If the point is null.
   * @since 0.0.1
   */
  public void putPixel(Vector2D point) {
    if (point != null) {
      int x = (int) Math.round(point.getX0());
      int y = (int) Math.round(point.getX1());

      if (x >= 0 && x < width && y >= 0 && y < height) {
        canvas[x][y] = 1;
      }
    } else {
      throw new IllegalArgumentException("Point cannot be null");

    }

  }


  /**
   * Gets the canvas array.
   *
   * @return The canvas array.
   * @since 0.0.1
   */
  public int[][] getCanvasArray() {
    return canvas;
  }

  /**
   * Clears the canvas, i.e., sets all pixels to 0.
   */
  public void clearCanvas() {
    for (int i = 0; i < width; i++) {
      for (int j = 0; j < height; j++) {
        canvas[i][j] = 0;
      }
    }
  }


  /**
   * Gets the width of the canvas.
   *
   * @return The width of the canvas.
   * @since 0.0.1
   */
  public int getWidth() {
    return width;
  }


  /**
   * Gets the height of the canvas.
   *
   * @return The height of the canvas.
   * @since 0.0.1
   */
  public int getHeight() {
    return height;
  }
}
